name: Publish package to the Maven Central Repository
on:
  label:
    types:
      - created
  #push:
  #  branches: [ main ]
jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        #cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Builds the release artifacts of the library
    - name: Release build
      run: ./gradlew sbbml:assembleRelease

    # Generates other artifacts 
    - name: Source jar and dokka
      run: ./gradlew androidSourcesJar androidJavadocJar

    # Runs upload, and then closes & releases the repository
    - name: Publish to MavenCentral
      run: ./gradlew sbbml:publishReleasePublicationToSonatypeRepository --stacktrace # use this cmd to avoid nexus release approve: --max-workers 1 closeAndReleaseSonatypeStagingRepository
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_STAGINGPROFILEID: ${{ secrets.SONATYPE_STAGINGPROFILEID }}
        PGP_KEY: ${{ secrets.PGP_KEY }}
        PGP_KEYID: ${{ secrets.PGP_KEYID }}
        PGP_PASSWORD: ${{ secrets.PGP_PASSWORD }}

